
[workspace]
resolver = "2"
members = ["crates/fabrica", "crates/ui"]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
fabrica = { path = "crates/fabrica" }
ui = { path = "crates/ui" }

anyhow = "1.0.102"
gpui = "0.2.2"
gpui-component = "0.5.1"
gpui-component-assets = "0.5.1"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
time = { version = "0.3", features = ["parsing", "formatting", "macros"] }
sqlx = { version = "0.8", default-features = false, features = [
    "sqlite",
    "macros",
    "migrate",
    "runtime-async-std",
] }
base64 = "0.22"

[workspace.lints.rust]
unexpected_cfgs = { level = "allow" }

[profile.dev]
debug = 1
incremental = true
codegen-units = 256

[profile.dev.build-override]
opt-level = 3

[profile.dev.package.sqlx-macros]
opt-level = 3
