[package]
name = "fabrica"
version = "0.1.0"
edition = "2024"
publish.workspace = true
license = "MIT"

[[bin]]
name = "fabrica"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui-component-assets.workspace = true
ui.workspace = true
serde.workspace = true
serde_json.workspace = true
